def isPowerOfTwo(n):
    if n==0:
        return False
    if n==1:
        return True
    def f(a):
        if a>n:
            return False
        if a==n:
            return True
        return f(a*2)
    return f(2)